AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
