version: '3.3'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/fleet-api:${MAPOTEMPO_VERSION:-56.0.0}
    ports:
      - "8084:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ./sync-gateway-config.json:/srv/app/docker/sync-gateway-config.json
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./production.rb:/srv/app/config/environments/development.rb
    restart: always
    links:
      - redis-cache
    environment:
      - APP_ENV=production # Switch to "development" for more traces
      - RAILS_LOG_TO_STDOUT=true
      - COUCHBASE_PASSWORD=123456 # Same password in couchbaseserver > healthcheck > test and in initialize-db.sh --rbac-password
      - SECRET_KEY_BASE=wieTipuij4RoaRei1AaGhohmutoh9ahGeeheith3cuquajah0oi2uux6Bie4uqu6leiwo9Ooquu7hiec6Coh1eemahng4ainap9seew8queid8sashoixigahsee1zie

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""

  couchbaseserver:
    image: couchbase/server:5.0.0
    ports:
      - "127.0.0.1:8091:8091" # Admin Web & API, internal access
#      - "8092:8092" # , internal access
#      - "11210:11210" # DB connection, internal access
    volumes:
      - ./couchbase-db:/opt/couchbase/var
    healthcheck:
      test: ["CMD-SHELL", "cbstats localhost:11210 -b fleet-prod -p 123456 raw warmup | grep -q complete"] # Same password in wrapper > environment > COUCHBASE_PASSWORD and in initialize-db.sh --rbac-password
      interval: 30s
      timeout: 10s
      retries: 50

  sync-gateway:
    build:
      context: sync-gateway
      dockerfile: Dockerfile
    image: sync-gateway:1.5.0
    ports:
      - "4984:4984" # API Rest for Users, open to Web
      - "127.0.0.1:4985:4985" # API Rest Admin, internal access : http://127.0.0.1:4985/_admin/db
    volumes:
      - ./sync-gateway-config.json:/etc/sync_gateway/config.json
    command: -adminInterface :4985 /etc/sync_gateway/config.json
    depends_on:
      - couchbaseserver
