common: &common
  hosts: localhost
  password: '123456'

development:
  <<: *common
  bucket: fleet-dev
  password: '123456'

test:
  <<: *common
  bucket: fleet-test
  password: '123456'

# set these environment variables on your production server
production:
  hosts: <%= ENV['COUCHBASE_HOST'] || ENV['COUCHBASE_HOSTS'] || 'couchbaseserver' %>
  bucket: <%= ENV['COUCHBASE_BUCKET'] || 'fleet-prod' %>
  password: <%= ENV['COUCHBASE_PASSWORD'] || '123456' %>
